# Discussion

These study found that exist a reduction in the seed germinability of *J. curcas* according to water imbibiton. It is suppose that seeds precise a mount of water for promote the germination but in these case the seeds submitted to water imbibition had a decrease in germination and an increase in the mean germination time. Also is observed during the time line of the experiment there was a increase in EC that reflect in lost the  seed germinability from seed steeping in water from 02 to 24 hours.

The seeds used in these experiment were stored dry and hence have very low levels of metabolism. During imbibition of water, they swell and metabolic activity increases. Hydration of tissue components during imbibition takes place in a not controlled way so that the reconstruction of internal structures of the cells and organelles was affected. So leakage of stored materials and enzymes, colouring, cracking or absence of cotyledons, and overall damage to the hypocotyl may occur during germination [@Hobbs1972Interaction; @pollock1969vigor]. The amount of the constituents of the leaked depended unequivocally on the initial water content of seeds; the lower moisture in seed at the initial water content show more leakage that no occur with seeds with the initial water content of 24.2% [@ISHIDA1988relationship]. This damage takes place in the early stages of imbibition [@Parrish1977Transient]. This indicates that membrane functions are restored, even though the activities of respiration and metabolism are restricted. Water molecules are semi bound and that mobile water necessary for metabolism is deficient for moisture contents between 12-24% [@Koizumi2008Role]. According to these the lost of viability can be explain for the initial seed water content of the seeds used in these experiment because they had an initial moisture around 8%. It is low water content according to moisture in harvest that is around 18% [@Pompelli_2010]. Also in other crops like soybean seeds water content is usually 10 to 20% at harvest and falls further during storage, seed water contents below 10% were shown to be desirable for long period storage because seeds stop their biological activities and the stored materials are consumed at a minimum level [@Windauer2007Hydrotime]. *J. curcas* seeds after 24 hour of imbibition arrive 6.5 times initial moisture as reported by [@ISHIDA1988relationship], dried seeds is elevated to a certain level, two or three times the dry weight of seeds, and this rapid increase of water is often accompanied by some deterioration of the tissues, called imbibitional damage. These damage is expressed as a reduced rate of germination and reduced yield of surviving plants. It can be the reason in decrease in the germination percentage in these research. It was reported that soybean seeds with the water content below 13% suffered seriously from imbibitional damage while those above 17% did not, where respiration and metabolic activity rapidly increase with the increase of moisture content [@ISHIDA1988relationship; @Vertucci1984Bound]. Imbibition damage results from the rapid entry of water into the cotyledons during imbibition, leading to cell death and high solute leakage from the seeds [@POWELL1978Damaging] and the extensive loss of cellular material and enzymes from the seeds [@Duke1981Role; @POWELL1981Physical] indicates extensive membrane disruption. The electrical conductivity was related with seed water content and the germination for these reason EC tests has been applied to detect vigor differences in many other grain legumes and indeed some other species [@hampton1995handbook]. The conductivity will increase as the laboratory germination falls, in addition to the reduced ability of germination seeds to retain cell contents [@matthews2006electrical]. In many reports on peas, the EC readings for lots have been found to relate significantly to field emergence [@POWELL1981Physical; @THORNTON1990Investigation].

To alleviate of the effects of soaking injury as a result of the increase in the moisture content of seeds before imbibition is related to the reduced binding energy of water molecules and the appearance of respiratory activity [@Vertucci1984Bound]. Slow and controlled hydration is essential as the first step in the reactivation of metabolic processes in the dry seed,leading to germination and growth. The EC would be developed and standardized for these species [@Abdullah1991Association; @Yaklich1979Evaluation; @POWELL1986Role]. Furthermore was reported than the relationship between field emergence and EC turned out to be not only interesting, but useful in practical seed technology [@matthews1967detection] as present in these work for *J. curcas*.
